# This is a basic workflow to help you get started with Actions

name: Code-Scanning

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 */3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 600
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build LBC Image
        run: |
          make IMG=action-image-lbc:latest docker-scan

      - name: Install trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.23.0

      - name: Use Trivy to Scan
        run: |
          echo "$(trivy image --format template --template '{{- $unknown := 0 }}{{- $low := 0 }}{{- $medium := 0 }}{{- $critical := 0 }}{{- $high := 0 }}{{- range . }}{{- range .Vulnerabilities }}{{- if  eq .Severity "CRITICAL" }}{{- $critical = add $critical 1 }}{{- end }}{{- if  eq .Severity "HIGH" }}{{- $high = add $high 1 }}{{- end }}{{- if  eq .Severity "UNKNOWN" }}{{- $unknown = add $unknown 1 }}{{- end }}{{- if  eq .Severity "LOW" }}{{- $low = add $low 1 }}{{- end }}{{- if  eq .Severity "MEDIUM" }}{{- $medium = add $medium 1 }}{{- end }}{{- end }}{{- end }}UNKNOWN_CVES={{ $unknown }},LOW_CVES={{ $low }},MEDIUM_CVES={{ $medium }},HIGH_CVES={{ $high }},CRITICAL_CVES={{ $critical }}' action-image-lbc:latest | tail -1 | tr ',' '\n')" >> $GITHUB_ENV

      - name: Publish HIGH_CVES to CW
        uses: aws-actions/action-cloudwatch-metrics@main
        env:
            AWS_DEFAULT_REGION: us-west-2
            AWS_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
        with:
          metric-name: aws-load-balancer-controller-code-scan-high
          metric-value: ${{ env.HIGH_CVES }}

      - name: Publish CRITICAL_CVES to CW
        uses: aws-actions/action-cloudwatch-metrics@main
        env:
            AWS_DEFAULT_REGION: us-west-2
            AWS_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
        with:
          metric-name: aws-load-balancer-controller-code-scan-critical
          metric-value: ${{ env.CRITICAL_CVES }}

      - name: Publish MEDIUM_CVES to CW
        uses: aws-actions/action-cloudwatch-metrics@main
        env:
            AWS_DEFAULT_REGION: us-west-2
            AWS_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
        with:
          metric-name: aws-load-balancer-controller-code-scan-medium
          metric-value: ${{ env.MEDIUM_CVES }}

      - name: Publish LOW_CVES to CW
        uses: aws-actions/action-cloudwatch-metrics@main
        env:
            AWS_DEFAULT_REGION: us-west-2
            AWS_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
        with:
          metric-name: aws-load-balancer-controller-code-scan-low
          metric-value: ${{ env.LOW_CVES }}

      - name: Publish UNKNOWN_CVES to CW
        uses: aws-actions/action-cloudwatch-metrics@main
        env:
            AWS_DEFAULT_REGION: us-west-2
            AWS_REGION: us-west-2
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
        with:
          metric-name: aws-load-balancer-controller-code-scan-unknown
          metric-value: ${{ env.UNKNOWN_CVES }}
